KoduCare/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KoduCare.Controllers
{
    public class HomeController : ApplicationController
    {
        //Home page
        public ActionResult Index()
        {
            return View();
        }

    }
}

KoduCare/Controllers/OrderController.cs
using KoduCare.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KoduCare.Controllers
{
    public class OrderController : ApplicationController
    {
        // Page with map
        public ActionResult Index()
        {

            return View();
        }

        //Page with order result
        public ActionResult AddOrder(Order order)
        {
            order.Date = DateTime.Now;
            order.UserIP = siteLocation.Ip;
            var result = dbService.Orders.AddOrder(order);
            order.Id = result;

            var UserTexts = new Dictionary<string, string>();
            UserTexts["ABC"] = System.Configuration.ConfigurationManager.AppSettings["ABC"];
            ViewBag.UserTexts = UserTexts;

            return View(order);
        }
    }
}

KoduCare/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="body-index">
    <div class="container">
        <div class="left-panel col-md-5">
            <div class="panel-pos">
                <div>Seriosly. Why can't the<br />doctor just come to me?</div>
                @*<a href="@Url.Action("Index","Order")">Get Doctor</a>*@
            </div>
        </div>
    </div>
</div>
<div class="instantly">
    <div class="container">
        <div class="row">
            <div class="instantly-text col-md-6">
                <div class="i-text">
                    <h2>Instantly shedule home doctor visits</h2>
                    <strong>Sick?</strong> Stay where you are! With Kodu Care
                    you can immediately request a caring,
                    board-certified physician visit you in the
                    comfort of your own home, office, or hole
                    within 2 hours.<br>
                    Learn <a href="#" id="hiw">How it Works</a> or <a href="#" id="sun">Sign Up Now</a>
                </div>
            </div>
            <div class="col-md-4 iphones">
                <div class="iphone6_1"></div>
                <div class="iphone6_2"></div>
            </div>
        </div>
    </div>
</div>
<div class="how_it_works">
    <div class="container">
        <div class="row">
            <h2>How it works:</h2>
            <div class="col-md-4 steps">
                <i class="mobile-ico"></i>
                <h3>1. Click "Book Doctor"</h3>
                <p>Follow the instructions<br>to request a doctor visit</p>
            </div>
            <div class="col-md-4 steps">
                <i class="clock-ico"></i>
                <h3>2. Shedule</h3>
                <p>Speak with the doctor who will call to confirm<br>your visit with in 15 minutes</p>
            </div>
            <div class="col-md-4 steps">
                <i class="ok-ico"></i>
                <h3>3. That's it!</h3>
                <p>Relax! You're in good hands. The doctor will<br>be there to see you withvin 2 hours</p>
            </div>
        </div>
    </div>
</div>
<div class="get_start">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h2>Get Started Here!</h2>
                <p>We're going to launch soon, if&nbsp;you&nbsp;wantto&nbsp;be&nbsp;in&nbsp;touch<br>please give us your email and zipode and you'll&nbsp;be&nbsp;the&nbsp;first&nbsp;to&nbsp;know<br>when we launch in your area.</p>
                <div id="mc_embed_signup">
                    <div class="response" id="mce-error-response" style="display:none"></div>
                    <div class="response" id="mce-success-response" style="display:none"></div>
                    <form action="http://koducare.us10.list-manage.com/subscribe/post?u=13c3991f3e1f82d3881de29de&amp;id=84aceb55fe" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate clearfix" target="_blank" novalidate>
                        <div class="mc-field-group first">
                            @*<label for="mce-EMAIL"></label>*@
                            <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" placeholder="E-mail">
                        </div>
                        <div class="mc-field-group second">
                            @*<label for="mce-ZIPC"></label>*@
                            <input type="text" value="" name="ZIPC" class="required" id="mce-ZIPC" placeholder="Zip Code">
                        </div>
                        <div style="position: absolute; left: -5000px;"><input type="text" name="b_13c3991f3e1f82d3881de29de_84aceb55fe" tabindex="-1" value=""></div>
                        <input type="submit" value="" name="subscribe" id="mc-embedded-subscribe" class="button send_mailchimp">
                    </form>
                </div>
                <script type='text/javascript' src='http://s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script>
                <script type='text/javascript'>(function ($) { window.fnames = new Array(); window.ftypes = new Array(); fnames[0] = 'EMAIL'; ftypes[0] = 'email'; fnames[1] = 'FNAME'; ftypes[1] = 'text'; fnames[2] = 'LNAME'; ftypes[2] = 'text'; fnames[3] = 'ZIPC'; ftypes[3] = 'zip'; }(jQuery)); var $mcj = jQuery.noConflict(true);</script>
            </div>
        </div>
    </div>
</div>
<div class="who_is">
    <div class="container">
        <div class="col-md-6 col-md-offset-3">
            <div class="text">
                <h2>Who is Kodu Care?</h2>
                <p>Kodu Care is a group of doctors, nerds, and  entrepreneurs who are passionate about making healthcare more convenient.</p>
            </div>
        </div>
    </div>
</div>
<div class="footer">
    <div class="container">
        <div class="col-md-1">
            <a href="#" class="footer_logo"></a>
        </div>
        <div class="col-md-3 col-md-offset-8 copyright">
            &copy; Kodu Care | all rights reserved<br>privacy policy | copyright
        </div>
    </div>
</div>